# application.yml
spring:
 datasource:
  application:
   name: flight-server
  driver-class-name: com.mysql.cj.jdbc.Driver
  password: ''
  url: jdbc:mysql://localhost:3306/airlines
  username: root
 jpa:
  hibernate:
   ddl-auto: update
  properties:
   hibernate:
    dialect: org.hibernate.dialect.MySQLDialect
  show-sql: true
server:
  port: 0
eureka:
 client:
  #Que quiero que se registre y me traiga ese registro
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
 instance:
  preferIpAddress: true

