# application.yml
server:
 port: 0

spring:
  application:
   name: flight-server
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ''
    url: jdbc:mysql://localhost:3306/airlines
    username: root

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
     hibernate:
    dialect: org.hibernate.dialect.MySQLDialect


eureka:
 client:
  #Que quiero que se registre y me traiga ese registro
  registerWithEureka: true
  fetchRegistry: true
  serviceUrl:
   defaultZone: http://localhost:8761/eureka
 instance:
  preferIpAddress: true

